apiVersion: v1
kind: Service
metadata:
  name: camel-app-service
spec:
  selector:
    app: camel-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
  