spring:
  application:
    name: camel
camel:
  springboot:
    main-run-controller: true
  servlet:
    mapping:
      context-path: /camel/*
  rest:
    component: servlet
    binding-mode: json
    data-format-property:
      prettyPrint: true
    enable-cors: true
    host: localhost
    port: 8080
    context-path: /camel
    api-context-path: api-doc
    api-property:
      'api.title': User API
      'api.version': 1.0.0



